### ISSUE TITLE
Error when fetching workfile from local directory

### ISSUE THREAD

**Issue by wkwi2r** [inab/WfExS-backend#139]
I'm running a local installation of WfExS with python 3.12.3.

The workflow file is as follows:

```
workflow_id: file:///home/wfexs/hello-workflows/cwl/hello-workflow.cwl
workflow_config:
  secure: false
  containerType: docker
# All the inputs must be URLs or CURIEs from identifiers.org
params:
  an_input:
    c-l-a-s-s: File
    url: file:///home/wfexs/hello-workflows/cwl/hello.yml
environment:
  SECRET_VARIABLE: "The secret content"
outputs:
  hello_output:
    c-l-a-s-s: File
```

I encountered the following exception:

```
Traceback (most recent call last):
  File "/home/wfexs/WfExS_python_build/WfExS-backend/WfExS-backend.py", line 22, in <module>
    main()
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/__main__.py", line 1697, in main
    stagedSetup = wfInstance.stageWorkDir()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/workflow.py", line 3664, in stageWorkDir
    self.materializeWorkflowAndContainers(
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/workflow.py", line 2267, in materializeWorkflowAndContainers
    self.setupEngine(
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/workflow.py", line 2176, in setupEngine
    self.fetchWorkflow(
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/workflow.py", line 2010, in fetchWorkflow
    ) = self.wfexs.cacheWorkflow(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/wfexs_backend.py", line 2203, in cacheWorkflow
    repoDir, repoEffectiveCheckout = self.doMaterializeRepo(
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/wfexs_backend.py", line 2511, in doMaterializeRepo
    ) = self._doMaterializeGitRepo(repo, doUpdate=doUpdate)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/wfexs_backend.py", line 2549, in _doMaterializeGitRepo
    repoDir, materialized_repo, metadata_array = gitFetcherInst.materialize_repo(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/fetchers/git.py", line 793, in materialize_repo
    raise FetcherException(errstr)
wfexs_backend.fetchers.FetcherException: ERROR: Unable to pull 'file:///home/wfexs/hello-workflows/cwl/hello-workflow.cwl' (tag 'main'). Retval 128
======
STDOUT
======

======
STDERR
======
Cloning into '/tmp/wfexsbwx4qrw1tmpcache/wf-cache/78b6c4c86e48ccf70fb07c3da8fc701066c78de2/b28b7af69320201d1cf206ebf28373980add1451'...
fatal: invalid gitfile format: /home/wfexs/hello-workflows/cwl/hello-workflow.cwl
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is `file` URL supported? If yes, appreciate if you can take a look at the exception.

PS: I've run the `WfExS-backend\workflow_examples\hello\hello_cwl.wfex.stage` and `WfExS-backend\workflow_examples\hello\hello_cwl_http.wfex.stage` (with Docker) without issues.

**Comment by jmfernandez** [comment]
It should be supported until some extent, as the fallback when no repository scheme (i.e. git related ones, swh from Software Heritage, ...) should be resolving against any supported fetching scheme. So, I have to study the code in order to realize why it is not behaving as expected in this case.
